const RAW_STORY_DATA = {
    title: "A Fragging in Texas",
    intro: "",
    paragraphs: [
        [1, "An opposum on the other side of the fire coughed into her paw."],
        [2, "A dark viscous substance splattered,"],
        [3, "consisting of a wet mixture of saliva and tar from many years tobacco use."],
        [4, "Harry's eyes were directed at the broken fragments of wood and kindling."],
        [5, "The dog rubbed their curled paws to maintain some semblance of warmth."],
        [6, "The scrapping of skin against skin, fur against fur."],
        [7, "None of it... none of it got rid of a dead cold feeling that rose from his ribs to his chest."],
        [8, "He could not feel warm in such a way as Lady Macbeth could not feel clean."],
        [9, "His breaths were scattered."],
        [10, "A few wisps of cold air fluttered from underneath his nostrils."],
        [11, "Bringing his paws closer to his face, as if he had come to prayer,"],
        [12, "he had not noticed his disposition had been noticed by Annie."],
        [13, "She spoke to Roman."],
        [14, "\"I'll keep watch.\""],
        [15, "There was a grunt of approval,"],
        [16, "before the cloth of his tent shut."],
        [17, "Annie adjusted the dark brim of her hat before sitting next to Harry."],
        [18, "She wore glasses due to her poor eyesight,"],
        [19, "and as such it wasn't the lifeless look in Harry's eyes that caught her attention,"],
        [20, "but the quiet whimpers that erupted from his neck."],
        [21, "She was sympathetic to Mr. Bleeding Heart."],
        [22, "A man as young as him would see many things in their life,"],
        [23, "but not many were as unfortunate to bare witness such depths of depravity."],
        [24, "Wrapping her arm around his back,"],
        [25, "she watched as the dog silently cried into their wrist."],
        [26, "Tear's cleaning nothing,"],
        [27, "except blurring the stain smudges of impurities left from weeks of travel on horse back."],
        [28, "As the lantern light faded from Romans tent,"],
        [29, "she looked into the distance at some suspicious sounds of foliage snapping."],
        [30, "But since that was where the horses were,"],
        [31, "there was not much to amount to concern."],
        [32, "Nevertheless, the silence was deafening."],
        [33, "She reached into her satchel with her other hand."],
        [34, "Inside was a bundle of dynamite,"],
        [35, "and a thread that required only the warmth provided from the dancing flames to be ignited."],
        [36, "It wasn't noticed immediately."],
        [37, "But, after she had brought it closer to her lap so that she could inspect it,"],
        [38, "it was as if the dogs whimpers had been silenced."],
        [39, "His heart beat had changed,"],
        [40, "fluttering like a farm chickens wings while caught in the mouth of a wild fox."],
        [41, "She was prescient to know he would ruin everything if he yelped."],
        [42, "The oppossum's comforting grip over the dogs back changed to her sinking her non-retractable claws deep into his shoulder."],
        [43, "Unlike the folktale of a vampire that took pleasure in biting her victims,"],
        [44, "Annie took no sadistic enjoyment in feeling Harry's warm blood coursing over her sickly fingers."],
        [45, "Annie could see the change in his breath through how the puffs of cold air were in staggered twos,"],
        [46, "coming out of his nostrils like that of a train exhaust."],
        [47, "She stared at him."],
        [48, "They were of the same mind."],
        [49, "She could read it in his eyes,"],
        [50, "the wobbling of the highlights of his eye like a constellation in the night sky."],
        [51, "There was a name to those thoughts,"],
        [52, "even if he was too scared to be thinking them."],
        [53, "But he did not have the will to act on them."],
        [54, "Epilogue"],
        [55, "The sound of an ignited piece of fuse hisses through the air."],
        [56, "It is daybreak,"],
        [57, "the opossum brings a lit stick of tobacco to their mouth."],
        [58, "She stares at the road ahead,"],
        [59, "and the trail from yesterday."],
        [60, "The next town was only a few miles from here."],
        [61, "Behind Annie,"],
        [62, "the dog led two horses out of the bush."],
        [63, "Roman's, and his own."],
        [64, "They would go on to continue their journey."],
        [65, "The clopping sound of hooves against dirt fading into a blur."],
        [66, "The bandits left the bush,"],
        [67, "with one less in their company."]
    ]
};