const RAW_STORY_DATA = {
    title: "A Fragging in Texas",
    intro: "",
    paragraphs: [
        [1, "An opposum on the other side of the fire coughed into her paw."],
        [2, "A dark viscous substance splattered, consisting of a wet mixture of saliva and tar from many years tobacco use."],
        [3, "Harry's eyes were directed at the broken fragments of wood and kindling."],
        [4, "The dog rubbed their curled paws to maintain some semblance of warmth."],
        [5, "The scrapping of skin against skin, fur against fur."],
        [6, "None of it... none of it got rid of a dead cold feeling that rose from his ribs to his chest."],
        [7, "He could not feel warm in such a way as Lady Macbeth could not feel clean."],
        [8, "His breaths were scattered."],
        [9, "A few wisps of cold air fluttered from underneath his nostrils."],
        [10, "Bringing his paws closer to his face, as if he had come to prayer, he had not noticed his disposition had been noticed by Annie."],
        [11, "She spoke to Roman."],
        [12, "\"I'll keep watch.\""],
        [13, "There was a grunt of approval, before the cloth of his tent shut."],
        [14, "Annie adjusted the dark brim of her hat before sitting next to Harry."],
        [15, "She wore glasses due to her poor eyesight, and as such it wasn't the lifeless look in Harry's eyes that caught her attention- but the quiet whimpers that erupted from his neck."],
        [16, "She was sympathetic to Mr. Bleeding Heart."],
        [17, "A man as young as him would see many things in their life, but not many were as unfortunate to bare witness such depths of depravity."],
        [18, "Wrapping her arm around his back, she watched as the dog silently cried into their wrist."],
        [19, "Tear's cleaning nothing, except blurring the stain smudges of impurities left from weeks of travel on horse back."],
        [20, "As the lantern light faded from Romans tent, she looked into the distance at some suspicious sounds of foliage snapping."],
        [21, "But since that was where the horses were, there was not much to amount to concern."],
        [22, "Nevertheless, the silence was deafening."],
        [23, "She reached into her satchel with her other hand."],
        [24, "Inside was a bundle of dynamite, and a thread that required only the warmth provided from the dancing flames to be ignited."],
        [25, "It wasn't noticed immediately."],
        [26, "But, after she had brought it closer to her lap so that she could inspect it, it was as if the dogs whimpers had been silenced."],
        [27, "His heart beat had changed, fluttering like a farm chickens wings while caught in the mouth of a wild fox."],
        [28, "She was prescient to know he would ruin everything if he yelped."],
        [29, "The oppossum's comforting grip over the dogs back changed to her sinking her non-retractable claws deep into his shoulder."],
        [30, "Unlike the folktale of a vampire that took pleasure in biting her victims, Annie took no sadistic enjoyment in feeling Harry's warm blood coursing over her sickly fingers."],
        [31, "Annie could see the change in his breath through how the puffs of cold air were in staggered twos, coming out of his nostrils like that of a train exhaust."],
        [32, "She stared at him."],
        [33, "They were of the same mind."],
        [34, "She could read it in his eyes, the wobbling of the highlights of his eye like a constellation in the night sky."],
        [35, "There was a name to those thoughts, even if he was too scared to be thinking them."],
        [36, "But he did not have the will to act on them."],
        [37, "Epilogue"],
        [38, "The sound of an ignited piece of fuse hisses through the air."],
        [39, "It is daybreak, the opossum brings a lit stick of tobacco to their mouth."],
        [40, "She stares at the road ahead, and the trail from yesterday."],
        [41, "The next town was only a few miles from here."],
        [42, "Behind Annie, the dog led two horses out of the bush."],
        [43, "Roman's, and his own."],
        [44, "They would go on to continue their journey."],
        [45, "The clopping sound of hooves against dirt fading into a blur."],
        [46, "The bandits left the bush, with one less in their company."]
    ]
};